name: flash_notification
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/ibragimov05/flash_notification
issue_tracker: https://github.com/ibragimov05/flash_notification/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
